-- Clothing Store - new customer Supabase initialization
-- AUTHORITATIVE NEW CUSTOMER DEPLOYMENT SNAPSHOT.
-- Run this file only in a brand-new, empty Supabase project.
-- For customer deployment: paste the whole file into Supabase SQL Editor and click Run once.
-- For development and upgrades: supabase/migrations remains the source of truth.
-- Do not run this file on an existing customer database.
-- Generated from the ordered migrations listed below.

-- ============================================================================
-- BEGIN MIGRATION: 20260702000000_baseline_store_schema.sql
-- ============================================================================
begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  sku text unique not null,
  name_cn text not null default '',
  name_gr text not null default '',
  name_en text not null default '',
  description_cn text not null default '',
  description_gr text not null default '',
  description_en text not null default '',
  category text not null,
  subcategory text not null default '',
  price numeric(10,2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  sizes text not null default '',
  size_stock jsonb not null default '{}'::jsonb check (jsonb_typeof(size_stock) = 'object'),
  image_url text not null default '',
  image_urls jsonb not null default '[]'::jsonb check (jsonb_typeof(image_urls) = 'array'),
  image_width integer,
  image_height integer,
  brand text not null default '',
  barcode text not null default '',
  ean text not null default '',
  vat numeric(5,2) not null default 24,
  color text not null default '',
  additional_image_urls text not null default '',
  skroutz_url text not null default '',
  material text not null default '',
  fit text not null default '',
  season text not null default '',
  mpn text not null default '',
  availability text not null default '',
  size_chart jsonb not null default '{}'::jsonb check (jsonb_typeof(size_chart) = 'object'),
  fit_type text not null default 'regular',
  style_tags text[] not null default '{}',
  ai_keywords text[] not null default '{}',
  material_verified boolean not null default false,
  category_path_en text not null default '',
  category_path_gr text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_sku_idx on public.products (sku);
create index if not exists products_created_at_idx on public.products (created_at desc);
create index if not exists products_category_idx on public.products (category);
create index if not exists products_category_subcategory_idx on public.products (category, subcategory);
create index if not exists products_is_active_idx on public.products (is_active);

drop trigger if exists products_updated_at on public.products;
create trigger products_updated_at before update on public.products
for each row execute function public.set_updated_at();

create table if not exists public.business_settings (
  id uuid primary key default gen_random_uuid(),
  business_name text not null default 'Fashion Boutique',
  logo_url text not null default '',
  hero_image_url text not null default '',
  description_cn text not null default '',
  description_en text not null default '',
  description_gr text not null default '',
  phone text not null default '',
  whatsapp text not null default '',
  instagram text not null default '',
  facebook text not null default '',
  tiktok text not null default '',
  address text not null default '',
  google_maps_url text not null default '',
  opening_hours text not null default '',
  footer_text text not null default '',
  enable_skroutz boolean not null default false,
  feed_min_stock integer not null default 1 check (feed_min_stock >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists settings_updated_at on public.business_settings;
create trigger settings_updated_at before update on public.business_settings
for each row execute function public.set_updated_at();

insert into public.business_settings (business_name, description_cn, description_en, description_gr)
select 'Fashion Boutique', '欢迎来到我们的在线商店。', 'Welcome to our online store.', 'Καλώς ήρθατε στο ηλεκτρονικό μας κατάστημα.'
where not exists (select 1 from public.business_settings);

create table if not exists public.product_categories (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name_cn text not null default '',
  name_en text not null default '',
  name_gr text not null default '',
  image_url text not null default '',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists product_categories_sort_order_idx on public.product_categories (sort_order);
drop trigger if exists categories_updated_at on public.product_categories;
create trigger categories_updated_at before update on public.product_categories
for each row execute function public.set_updated_at();

create table if not exists public.product_subcategories (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.product_categories(id) on delete cascade,
  slug text not null,
  name_cn text not null default '',
  name_en text not null default '',
  name_gr text not null default '',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (category_id, slug)
);

create index if not exists product_subcategories_category_id_idx on public.product_subcategories (category_id);
create index if not exists product_subcategories_sort_order_idx on public.product_subcategories (sort_order);
drop trigger if exists subcategories_updated_at on public.product_subcategories;
create trigger subcategories_updated_at before update on public.product_subcategories
for each row execute function public.set_updated_at();

alter table public.products enable row level security;
alter table public.business_settings enable row level security;
alter table public.product_categories enable row level security;
alter table public.product_subcategories enable row level security;

revoke all on table public.products, public.business_settings, public.product_categories, public.product_subcategories from anon, authenticated;
grant select on table public.products, public.business_settings, public.product_categories, public.product_subcategories to anon, authenticated;
grant select, insert, update, delete on table public.products, public.business_settings, public.product_categories, public.product_subcategories to service_role;
grant usage, select on sequence public.products_id_seq to service_role;

drop policy if exists "Public read active products" on public.products;
create policy "Public read active products" on public.products for select to anon, authenticated
using (is_active = true);

drop policy if exists "Public read business settings" on public.business_settings;
create policy "Public read business settings" on public.business_settings for select to anon, authenticated
using (true);

drop policy if exists "Public read active categories" on public.product_categories;
create policy "Public read active categories" on public.product_categories for select to anon, authenticated
using (is_active = true);

drop policy if exists "Public read active subcategories" on public.product_subcategories;
create policy "Public read active subcategories" on public.product_subcategories for select to anon, authenticated
using (is_active = true);

insert into public.product_categories (slug, name_cn, name_en, name_gr, sort_order) values
  ('women', '女装', 'Women', 'Γυναικεία', 1),
  ('men', '男装', 'Men', 'Ανδρικά', 2),
  ('shoes', '鞋子', 'Shoes', 'Παπούτσια', 3),
  ('bags', '包包', 'Bags', 'Τσάντες', 4),
  ('luggage', '行李箱', 'Luggage', 'Βαλίτσες', 5),
  ('hats', '帽子', 'Hats', 'Καπέλα', 6),
  ('jewelry', '首饰', 'Jewelry', 'Κοσμήματα', 7),
  ('other', '其他', 'Other', 'Άλλα', 8)
on conflict (slug) do nothing;

insert into public.product_subcategories (category_id, slug, name_cn, name_en, name_gr, sort_order)
select c.id, s.slug, s.name_cn, s.name_en, s.name_gr, s.sort_order
from public.product_categories c
cross join lateral (
  values
    ('women', 'dresses', '连衣裙', 'Dresses', 'Φορέματα', 1),
    ('women', 'tops', '上衣', 'Tops', 'Τοπ', 2),
    ('women', 'shirts', '衬衫', 'Shirts', 'Πουκάμισα', 3),
    ('women', 'hoodies', '卫衣', 'Hoodies', 'Φούτερ', 4),
    ('women', 'jackets', '外套', 'Jackets', 'Μπουφάν', 5),
    ('women', 'trousers', '长裤', 'Trousers', 'Παντελόνια', 6),
    ('women', 'skirts', '半身裙', 'Skirts', 'Φούστες', 7),
    ('men', 'tshirts', 'T恤', 'T-shirts', 'T-shirts', 1),
    ('men', 'shirts', '衬衫', 'Shirts', 'Πουκάμισα', 2),
    ('men', 'hoodies', '卫衣', 'Hoodies', 'Φούτερ', 3),
    ('men', 'jackets', '外套', 'Jackets', 'Μπουφάν', 4),
    ('men', 'trousers', '长裤', 'Trousers', 'Παντελόνια', 5),
    ('men', 'jeans', '牛仔裤', 'Jeans', 'Τζιν', 6),
    ('men', 'shorts', '短裤', 'Shorts', 'Σορτς', 7),
    ('shoes', 'sneakers', '运动鞋', 'Sneakers', 'Sneakers', 1),
    ('shoes', 'boots', '靴子', 'Boots', 'Μπότες', 2),
    ('shoes', 'sandals', '凉鞋', 'Sandals', 'Σανδάλια', 3),
    ('shoes', 'heels', '高跟鞋', 'Heels', 'Γόβες', 4),
    ('bags', 'handbags', '手提包', 'Handbags', 'Τσάντες χειρός', 1),
    ('bags', 'backpacks', '双肩包', 'Backpacks', 'Σακίδια', 2),
    ('bags', 'wallets', '钱包', 'Wallets', 'Πορτοφόλια', 3),
    ('luggage', 'suitcases', '行李箱', 'Suitcases', 'Βαλίτσες', 1),
    ('luggage', 'travel_bags', '旅行包', 'Travel Bags', 'Ταξιδιωτικές τσάντες', 2),
    ('hats', 'caps', '鸭舌帽', 'Caps', 'Καπέλα', 1),
    ('hats', 'beanies', '针织帽', 'Beanies', 'Σκούφοι', 2),
    ('jewelry', 'necklaces', '项链', 'Necklaces', 'Κολιέ', 1),
    ('jewelry', 'bracelets', '手链', 'Bracelets', 'Βραχιόλια', 2),
    ('jewelry', 'earrings', '耳环', 'Earrings', 'Σκουλαρίκια', 3),
    ('jewelry', 'rings', '戒指', 'Rings', 'Δαχτυλίδια', 4),
    ('other', 'accessories', '配饰', 'Accessories', 'Αξεσουάρ', 1)
) as s(category_slug, slug, name_cn, name_en, name_gr, sort_order)
where c.slug = s.category_slug
on conflict (category_id, slug) do nothing;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = excluded.public;

commit;

-- END MIGRATION: 20260702000000_baseline_store_schema.sql

-- ============================================================================
-- BEGIN MIGRATION: 20260703_add_erp_inventory_phase_1.sql
-- ============================================================================
begin;

create extension if not exists pgcrypto;

create table if not exists public.inventory_locations (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  type text not null default 'store',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint inventory_locations_type_check
    check (type in ('store', 'warehouse', 'online', 'other'))
);

insert into public.inventory_locations (code, name, type, active, sort_order)
values ('MAIN_STORE', 'Main Store', 'store', true, 0)
on conflict (code) do update
set name = excluded.name,
    type = excluded.type,
    active = true,
    updated_at = now();

create table if not exists public.product_variants (
  id uuid primary key default gen_random_uuid(),
  product_id bigint not null references public.products(id) on delete cascade,
  variant_sku text not null unique,
  barcode text,
  size text,
  color text,
  cost_price numeric(10,2),
  price numeric(10,2),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists product_variants_barcode_unique
on public.product_variants (barcode)
where barcode is not null and btrim(barcode) <> '';

create unique index if not exists product_variants_product_size_color_unique
on public.product_variants (
  product_id,
  coalesce(size, ''),
  coalesce(color, '')
);

create index if not exists product_variants_product_id_idx
on public.product_variants(product_id);

create table if not exists public.inventory_balances (
  id uuid primary key default gen_random_uuid(),
  variant_id uuid not null references public.product_variants(id) on delete cascade,
  location_id uuid not null references public.inventory_locations(id) on delete cascade,
  quantity_on_hand integer not null default 0,
  quantity_reserved integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (variant_id, location_id),
  constraint inventory_balances_quantity_check
    check (
      quantity_on_hand >= 0
      and quantity_reserved >= 0
      and quantity_reserved <= quantity_on_hand
    )
);

create index if not exists inventory_balances_variant_id_idx
on public.inventory_balances(variant_id);

create index if not exists inventory_balances_location_id_idx
on public.inventory_balances(location_id);

create table if not exists public.stock_movements (
  id uuid primary key default gen_random_uuid(),
  variant_id uuid not null references public.product_variants(id) on delete restrict,
  location_id uuid not null references public.inventory_locations(id) on delete restrict,
  movement_type text not null,
  quantity_delta integer not null,
  quantity_before integer not null,
  quantity_after integer not null,
  reason text not null,
  source_type text,
  source_id text,
  idempotency_key text unique,
  created_by text,
  created_at timestamptz not null default now(),
  constraint stock_movements_type_check
    check (movement_type in (
      'initial_migration',
      'manual_adjustment',
      'sale',
      'return',
      'transfer_in',
      'transfer_out',
      'reservation',
      'release_reservation',
      'correction'
    )),
  constraint stock_movements_reason_not_blank_check
    check (btrim(reason) <> '')
);

create index if not exists stock_movements_variant_id_idx
on public.stock_movements(variant_id);

create index if not exists stock_movements_location_id_idx
on public.stock_movements(location_id);

create index if not exists stock_movements_created_at_idx
on public.stock_movements(created_at desc);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor text,
  action text not null,
  entity text not null,
  entity_id text,
  before jsonb,
  after jsonb,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_entity_idx
on public.audit_logs(entity, entity_id);

create index if not exists audit_logs_created_at_idx
on public.audit_logs(created_at desc);

alter table public.inventory_locations enable row level security;
alter table public.product_variants enable row level security;
alter table public.inventory_balances enable row level security;
alter table public.stock_movements enable row level security;
alter table public.audit_logs enable row level security;

grant usage on schema public to service_role;
grant select, insert, update, delete on public.inventory_locations to service_role;
grant select, insert, update, delete on public.product_variants to service_role;
grant select, insert, update, delete on public.inventory_balances to service_role;
grant select, insert, update, delete on public.stock_movements to service_role;
grant select, insert, update, delete on public.audit_logs to service_role;

with main_location as (
  select id
  from public.inventory_locations
  where code = 'MAIN_STORE'
  limit 1
),
safe_products as (
  select
    p.*,
    case
      when p.size_stock is not null and jsonb_typeof(p.size_stock) = 'object'
      then p.size_stock
      else '{}'::jsonb
    end as safe_size_stock
  from public.products p
  where p.sku is not null and btrim(p.sku) <> ''
),
valid_size_rows as (
  select
    p.id as product_id,
    p.sku as product_sku,
    p.price,
    p.color,
    p.is_active,
    s.key as size,
    greatest(s.value::int, 0) as quantity,
    row_number() over (partition by p.id order by s.key) as sort_order
  from safe_products p
  cross join lateral jsonb_each_text(p.safe_size_stock) s(key, value)
  where s.value ~ '^-?[0-9]+$'
),
one_size_products as (
  select
    p.id as product_id,
    p.sku as product_sku,
    p.price,
    p.color,
    p.barcode,
    p.is_active,
    'ONE SIZE'::text as size,
    greatest(coalesce(p.stock, 0), 0) as quantity,
    0 as sort_order
  from safe_products p
  where not exists (
    select 1
    from valid_size_rows r
    where r.product_id = p.id
  )
),
all_variants as (
  select
    product_id,
    product_sku,
    null::text as barcode,
    size,
    color,
    price,
    coalesce(is_active, true) as active,
    sort_order,
    quantity,
    product_sku || '-' || upper(regexp_replace(size, '[^a-zA-Z0-9]+', '-', 'g')) as variant_sku
  from valid_size_rows
  union all
  select
    product_id,
    product_sku,
    nullif(btrim(barcode), '') as barcode,
    size,
    color,
    price,
    coalesce(is_active, true) as active,
    sort_order,
    quantity,
    product_sku as variant_sku
  from one_size_products
),
inserted_variants as (
  insert into public.product_variants (
    product_id,
    variant_sku,
    barcode,
    size,
    color,
    price,
    active,
    sort_order
  )
  select
    product_id,
    variant_sku,
    barcode,
    size,
    color,
    price,
    active,
    sort_order
  from all_variants
  on conflict (variant_sku) do update
  set
    product_id = excluded.product_id,
    barcode = excluded.barcode,
    size = excluded.size,
    color = excluded.color,
    price = excluded.price,
    active = excluded.active,
    sort_order = excluded.sort_order,
    updated_at = now()
  returning id, product_id, variant_sku, size
),
variant_quantities as (
  select
    iv.id as variant_id,
    ml.id as location_id,
    av.quantity
  from inserted_variants iv
  join all_variants av
    on av.variant_sku = iv.variant_sku
  cross join main_location ml
),
upsert_balances as (
  insert into public.inventory_balances (
    variant_id,
    location_id,
    quantity_on_hand,
    quantity_reserved,
    updated_at
  )
  select
    variant_id,
    location_id,
    quantity,
    0,
    now()
  from variant_quantities
  on conflict (variant_id, location_id) do update
  set
    quantity_on_hand = excluded.quantity_on_hand,
    quantity_reserved = least(public.inventory_balances.quantity_reserved, excluded.quantity_on_hand),
    updated_at = now()
  returning variant_id, location_id, quantity_on_hand
)
insert into public.stock_movements (
  variant_id,
  location_id,
  movement_type,
  quantity_delta,
  quantity_before,
  quantity_after,
  reason,
  source_type,
  source_id,
  idempotency_key,
  created_by
)
select
  b.variant_id,
  b.location_id,
  'initial_migration',
  b.quantity_on_hand,
  0,
  b.quantity_on_hand,
  'Initial migration from products.stock / products.size_stock',
  'migration',
  'erp_phase_1',
  'initial_migration:' || b.variant_id::text || ':' || b.location_id::text,
  'system'
from upsert_balances b
on conflict (idempotency_key) do nothing;

commit;

-- END MIGRATION: 20260703_add_erp_inventory_phase_1.sql

-- ============================================================================
-- BEGIN MIGRATION: 20260704_add_pos_phase_1_tables.sql
-- ============================================================================
begin;

create extension if not exists pgcrypto;

create table if not exists public.sales_orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null,
  status text not null default 'completed',
  source text not null default 'pos',
  subtotal numeric(10,2) not null default 0,
  discount_total numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  currency text not null default 'EUR',
  payment_status text not null default 'paid',
  idempotency_key text not null,
  created_by text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  voided_at timestamptz,
  refunded_at timestamptz,
  constraint sales_orders_order_number_unique unique (order_number),
  constraint sales_orders_idempotency_key_unique unique (idempotency_key),
  constraint sales_orders_status_check
    check (status in ('completed', 'voided', 'refunded')),
  constraint sales_orders_source_check
    check (source in ('pos', 'manual')),
  constraint sales_orders_payment_status_check
    check (payment_status in ('paid', 'voided', 'refunded')),
  constraint sales_orders_amounts_check
    check (
      subtotal >= 0
      and discount_total >= 0
      and total >= 0
    )
);

create table if not exists public.sales_order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.sales_orders(id) on delete restrict,
  product_id bigint not null references public.products(id) on delete restrict,
  variant_id uuid not null references public.product_variants(id) on delete restrict,
  product_sku text not null,
  variant_sku text not null,
  barcode text,
  name text not null,
  size text,
  color text,
  quantity integer not null,
  unit_price numeric(10,2) not null,
  discount_total numeric(10,2) not null default 0,
  line_total numeric(10,2) not null,
  created_at timestamptz not null default now(),
  constraint sales_order_items_quantity_check
    check (quantity > 0),
  constraint sales_order_items_amounts_check
    check (
      unit_price >= 0
      and discount_total >= 0
      and line_total >= 0
    )
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.sales_orders(id) on delete restrict,
  method text not null,
  amount numeric(10,2) not null,
  currency text not null default 'EUR',
  status text not null default 'paid',
  provider text,
  provider_reference text,
  raw_response jsonb,
  created_at timestamptz not null default now(),
  constraint payments_method_check
    check (method in ('cash', 'card', 'other')),
  constraint payments_status_check
    check (status in ('paid', 'failed', 'refunded', 'voided')),
  constraint payments_amount_check
    check (amount >= 0)
);

create index if not exists sales_orders_created_at_idx
on public.sales_orders(created_at desc);

create index if not exists sales_orders_status_idx
on public.sales_orders(status);

create index if not exists sales_order_items_order_id_idx
on public.sales_order_items(order_id);

create index if not exists sales_order_items_product_id_idx
on public.sales_order_items(product_id);

create index if not exists sales_order_items_variant_id_idx
on public.sales_order_items(variant_id);

create index if not exists sales_order_items_variant_sku_idx
on public.sales_order_items(variant_sku);

create index if not exists payments_order_id_idx
on public.payments(order_id);

create index if not exists payments_method_idx
on public.payments(method);

create index if not exists payments_created_at_idx
on public.payments(created_at desc);

alter table public.sales_orders enable row level security;
alter table public.sales_order_items enable row level security;
alter table public.payments enable row level security;

revoke all on table public.sales_orders from anon, authenticated;
revoke all on table public.sales_order_items from anon, authenticated;
revoke all on table public.payments from anon, authenticated;

grant select, insert, update, delete on table public.sales_orders to service_role;
grant select, insert, update, delete on table public.sales_order_items to service_role;
grant select, insert, update, delete on table public.payments to service_role;

commit;

-- END MIGRATION: 20260704_add_pos_phase_1_tables.sql

-- ============================================================================
-- BEGIN MIGRATION: 20260705000100_add_pos_rpc_functions.sql
-- ============================================================================
begin;

create extension if not exists pgcrypto;

create schema if not exists app_private;

revoke all on schema app_private from public;
grant usage on schema app_private to service_role;

create or replace function app_private.pos_sync_legacy_stock_from_erp(
  p_product_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_location_id uuid;
  v_stock integer := 0;
  v_size_stock jsonb := '{"ONE SIZE": 0}'::jsonb;
  v_sizes text := 'ONE SIZE';
begin
  if p_product_id is null then
    raise exception 'product_id is required';
  end if;

  select id
    into v_location_id
  from public.inventory_locations
  where code = 'MAIN_STORE'
  limit 1;

  if v_location_id is null then
    raise exception 'MAIN_STORE inventory location is missing';
  end if;

  with active_variants as (
    select
      coalesce(nullif(btrim(v.size), ''), 'ONE SIZE') as size,
      v.sort_order,
      coalesce(b.quantity_on_hand, 0)::integer as quantity_on_hand
    from public.product_variants v
    left join public.inventory_balances b
      on b.variant_id = v.id
     and b.location_id = v_location_id
    where v.product_id = p_product_id
      and v.active is distinct from false
  ),
  size_totals as (
    select
      size,
      min(sort_order) as sort_order,
      sum(quantity_on_hand)::integer as quantity_on_hand
    from active_variants
    group by size
  )
  select
    coalesce(sum(quantity_on_hand), 0)::integer,
    coalesce(jsonb_object_agg(size, quantity_on_hand order by sort_order, size), '{"ONE SIZE": 0}'::jsonb),
    coalesce(string_agg(size, ',' order by sort_order, size), 'ONE SIZE')
    into v_stock, v_size_stock, v_sizes
  from size_totals;

  update public.products
  set
    stock = v_stock,
    size_stock = v_size_stock,
    sizes = v_sizes
  where id = p_product_id;

  if not found then
    raise exception 'product % was not found for legacy stock sync', p_product_id;
  end if;

  return jsonb_build_object(
    'product_id', p_product_id,
    'stock', v_stock,
    'size_stock', v_size_stock,
    'sizes', v_sizes
  );
end;
$$;

create or replace function app_private.pos_order_payload(
  p_order_id uuid,
  p_already_processed boolean default false
)
returns jsonb
language sql
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'already_processed', coalesce(p_already_processed, false),
    'order', jsonb_build_object(
      'id', o.id,
      'order_number', o.order_number,
      'status', o.status,
      'payment_status', o.payment_status,
      'subtotal', o.subtotal,
      'discount_total', o.discount_total,
      'total', o.total,
      'currency', o.currency,
      'created_at', o.created_at,
      'completed_at', o.completed_at,
      'voided_at', o.voided_at,
      'refunded_at', o.refunded_at
    ),
    'items', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', i.id,
          'product_id', i.product_id,
          'variant_id', i.variant_id,
          'product_sku', i.product_sku,
          'variant_sku', i.variant_sku,
          'barcode', i.barcode,
          'name', i.name,
          'size', i.size,
          'color', i.color,
          'quantity', i.quantity,
          'unit_price', i.unit_price,
          'discount_total', i.discount_total,
          'line_total', i.line_total
        )
        order by i.created_at, i.id
      )
      from public.sales_order_items i
      where i.order_id = o.id
    ), '[]'::jsonb),
    'payments', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', p.id,
          'method', p.method,
          'amount', p.amount,
          'currency', p.currency,
          'status', p.status,
          'created_at', p.created_at
        )
        order by p.created_at, p.id
      )
      from public.payments p
      where p.order_id = o.id
    ), '[]'::jsonb),
    'affected_product_ids', coalesce((
      select jsonb_agg(distinct i.product_id)
      from public.sales_order_items i
      where i.order_id = o.id
    ), '[]'::jsonb),
    'affected_skus', coalesce((
      select jsonb_agg(distinct i.product_sku)
      from public.sales_order_items i
      where i.order_id = o.id
        and i.product_sku is not null
        and btrim(i.product_sku) <> ''
    ), '[]'::jsonb)
  )
  from public.sales_orders o
  where o.id = p_order_id;
$$;

create or replace function public.pos_checkout_rpc(
  p_client_request_id text,
  p_payment_method text,
  p_items jsonb,
  p_discount_total numeric default 0,
  p_notes text default null,
  p_created_by text default 'admin'
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_client_request_id text := btrim(coalesce(p_client_request_id, ''));
  v_payment_method text := btrim(coalesce(p_payment_method, ''));
  v_created_by text := nullif(btrim(coalesce(p_created_by, 'admin')), '');
  v_idempotency_key text;
  v_existing_order_id uuid;
  v_location_id uuid;
  v_order_id uuid;
  v_order_number text;
  v_subtotal numeric(10,2) := 0;
  v_discount_total numeric(10,2) := coalesce(p_discount_total, 0);
  v_total numeric(10,2) := 0;
  v_item_count integer := 0;
  v_row record;
  v_attempt integer;
begin
  if v_client_request_id = '' then
    raise exception 'client_request_id is required';
  end if;

  if v_payment_method not in ('cash', 'card', 'other') then
    raise exception 'payment_method must be cash, card, or other';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'items must be a non-empty jsonb array';
  end if;

  if v_discount_total < 0 then
    raise exception 'discount_total cannot be negative';
  end if;

  v_idempotency_key := 'pos_sale:' || v_client_request_id;

  select id
    into v_existing_order_id
  from public.sales_orders
  where idempotency_key = v_idempotency_key
  limit 1;

  if v_existing_order_id is not null then
    return app_private.pos_order_payload(v_existing_order_id, true);
  end if;

  select id
    into v_location_id
  from public.inventory_locations
  where code = 'MAIN_STORE'
  limit 1;

  if v_location_id is null then
    raise exception 'MAIN_STORE inventory location is missing';
  end if;

  create temporary table if not exists pos_rpc_items (
    variant_id uuid primary key,
    quantity integer not null check (quantity > 0)
  ) on commit drop;

  create temporary table if not exists pos_rpc_checkout_rows (
    variant_id uuid primary key,
    product_id bigint not null,
    balance_id uuid not null,
    product_sku text not null,
    variant_sku text not null,
    barcode text,
    name text not null,
    size text,
    color text,
    quantity integer not null,
    unit_price numeric(10,2) not null,
    line_total numeric(10,2) not null,
    quantity_before integer not null,
    quantity_reserved integer not null,
    quantity_after integer not null
  ) on commit drop;

  truncate table pos_rpc_items;
  truncate table pos_rpc_checkout_rows;

  insert into pos_rpc_items (variant_id, quantity)
  select
    coalesce(item->>'variantId', item->>'variant_id')::uuid as variant_id,
    sum((item->>'quantity')::integer)::integer as quantity
  from jsonb_array_elements(p_items) item
  where coalesce(item->>'variantId', item->>'variant_id') is not null
    and (item->>'quantity') ~ '^[0-9]+$'
    and (item->>'quantity')::integer > 0
  group by coalesce(item->>'variantId', item->>'variant_id')::uuid;

  select count(*) into v_item_count from pos_rpc_items;
  if v_item_count = 0 then
    raise exception 'items must include variantId and positive integer quantity';
  end if;

  for v_row in
    select
      i.variant_id,
      i.quantity,
      v.product_id,
      v.variant_sku,
      v.barcode,
      v.size,
      v.color,
      v.price as variant_price,
      v.active as variant_active,
      p.sku as product_sku,
      p.name_cn,
      p.name_en,
      p.name_gr,
      p.price as product_price,
      p.is_active as product_active,
      b.id as balance_id,
      b.quantity_on_hand,
      b.quantity_reserved
    from pos_rpc_items i
    join public.product_variants v on v.id = i.variant_id
    join public.products p on p.id = v.product_id
    join public.inventory_balances b
      on b.variant_id = v.id
     and b.location_id = v_location_id
    order by i.variant_id
    for update of b
  loop
    if v_row.variant_active is false then
      raise exception 'variant % is inactive', v_row.variant_sku;
    end if;

    if v_row.product_active is false then
      raise exception 'product % is inactive', v_row.product_sku;
    end if;

    if (v_row.quantity_on_hand - v_row.quantity_reserved) < v_row.quantity then
      raise exception 'insufficient stock for %, requested %, available %',
        v_row.variant_sku,
        v_row.quantity,
        greatest(v_row.quantity_on_hand - v_row.quantity_reserved, 0);
    end if;

    insert into pos_rpc_checkout_rows (
      variant_id,
      product_id,
      balance_id,
      product_sku,
      variant_sku,
      barcode,
      name,
      size,
      color,
      quantity,
      unit_price,
      line_total,
      quantity_before,
      quantity_reserved,
      quantity_after
    )
    values (
      v_row.variant_id,
      v_row.product_id,
      v_row.balance_id,
      coalesce(nullif(btrim(v_row.product_sku), ''), v_row.variant_sku),
      v_row.variant_sku,
      nullif(btrim(coalesce(v_row.barcode, '')), ''),
      coalesce(
        nullif(btrim(coalesce(v_row.name_cn, '')), ''),
        nullif(btrim(coalesce(v_row.name_en, '')), ''),
        nullif(btrim(coalesce(v_row.name_gr, '')), ''),
        v_row.product_sku,
        v_row.variant_sku
      ),
      nullif(btrim(coalesce(v_row.size, '')), ''),
      nullif(btrim(coalesce(v_row.color, '')), ''),
      v_row.quantity,
      round(coalesce(v_row.variant_price, v_row.product_price, 0)::numeric, 2),
      round(coalesce(v_row.variant_price, v_row.product_price, 0)::numeric * v_row.quantity, 2),
      v_row.quantity_on_hand,
      v_row.quantity_reserved,
      v_row.quantity_on_hand - v_row.quantity
    );
  end loop;

  if (select count(*) from pos_rpc_checkout_rows) <> v_item_count then
    raise exception 'one or more variants were not found or do not have MAIN_STORE balance';
  end if;

  select coalesce(sum(line_total), 0)::numeric(10,2)
    into v_subtotal
  from pos_rpc_checkout_rows;

  if v_discount_total > v_subtotal then
    raise exception 'discount_total cannot be greater than subtotal';
  end if;

  v_total := round(v_subtotal - v_discount_total, 2);

  for v_attempt in 1..5 loop
    begin
      v_order_number :=
        'POS-' || to_char(now(), 'YYYYMMDD-HH24MISS') || '-' ||
        upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));

      insert into public.sales_orders (
        order_number,
        status,
        source,
        subtotal,
        discount_total,
        total,
        currency,
        payment_status,
        idempotency_key,
        created_by,
        notes,
        completed_at
      )
      values (
        v_order_number,
        'completed',
        'pos',
        v_subtotal,
        v_discount_total,
        v_total,
        'EUR',
        'paid',
        v_idempotency_key,
        coalesce(v_created_by, 'admin'),
        nullif(btrim(coalesce(p_notes, '')), ''),
        now()
      )
      returning id into v_order_id;

      exit;
    exception
      when unique_violation then
        select id
          into v_existing_order_id
        from public.sales_orders
        where idempotency_key = v_idempotency_key
        limit 1;

        if v_existing_order_id is not null then
          return app_private.pos_order_payload(v_existing_order_id, true);
        end if;

        if v_attempt = 5 then
          raise;
        end if;
    end;
  end loop;

  insert into public.sales_order_items (
    order_id,
    product_id,
    variant_id,
    product_sku,
    variant_sku,
    barcode,
    name,
    size,
    color,
    quantity,
    unit_price,
    discount_total,
    line_total
  )
  select
    v_order_id,
    product_id,
    variant_id,
    product_sku,
    variant_sku,
    barcode,
    name,
    size,
    color,
    quantity,
    unit_price,
    0,
    line_total
  from pos_rpc_checkout_rows;

  insert into public.payments (
    order_id,
    method,
    amount,
    currency,
    status
  )
  values (
    v_order_id,
    v_payment_method,
    v_total,
    'EUR',
    'paid'
  );

  update public.inventory_balances b
  set
    quantity_on_hand = r.quantity_after,
    updated_at = now()
  from pos_rpc_checkout_rows r
  where b.id = r.balance_id;

  insert into public.stock_movements (
    variant_id,
    location_id,
    movement_type,
    quantity_delta,
    quantity_before,
    quantity_after,
    reason,
    source_type,
    source_id,
    idempotency_key,
    created_by
  )
  select
    r.variant_id,
    v_location_id,
    'sale',
    0 - r.quantity,
    r.quantity_before,
    r.quantity_after,
    'POS sale',
    'pos_sale',
    v_order_id::text,
    v_idempotency_key || ':' || r.variant_id::text,
    coalesce(v_created_by, 'admin')
  from pos_rpc_checkout_rows r;

  for v_row in
    select distinct product_id, product_sku
    from pos_rpc_checkout_rows
  loop
    perform app_private.pos_sync_legacy_stock_from_erp(v_row.product_id);
  end loop;

  return app_private.pos_order_payload(v_order_id, false);
end;
$$;

create or replace function public.pos_void_rpc(
  p_order_id uuid,
  p_client_request_id text,
  p_reason text,
  p_created_by text default 'admin'
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_client_request_id text := btrim(coalesce(p_client_request_id, ''));
  v_reason text := btrim(coalesce(p_reason, ''));
  v_created_by text := nullif(btrim(coalesce(p_created_by, 'admin')), '');
  v_order record;
  v_location_id uuid;
  v_existing_void_movement_id uuid;
  v_row record;
  v_idempotency_prefix text;
  v_restored_items jsonb := '[]'::jsonb;
begin
  if p_order_id is null then
    raise exception 'order_id is required';
  end if;

  if v_client_request_id = '' then
    raise exception 'client_request_id is required';
  end if;

  if length(v_reason) < 3 then
    raise exception 'reason is required and must be at least 3 characters';
  end if;

  select *
    into v_order
  from public.sales_orders
  where id = p_order_id
  for update;

  if not found then
    raise exception 'POS order was not found';
  end if;

  if v_order.status = 'voided' then
    return app_private.pos_order_payload(v_order.id, true)
      || jsonb_build_object('restored_items', '[]'::jsonb);
  end if;

  if v_order.status = 'refunded' then
    raise exception 'refunded order cannot be voided';
  end if;

  if v_order.status <> 'completed' then
    raise exception 'only completed orders can be voided';
  end if;

  select id
    into v_existing_void_movement_id
  from public.stock_movements
  where source_type = 'pos_void'
    and source_id = p_order_id::text
  limit 1;

  if v_existing_void_movement_id is not null then
    update public.sales_orders
    set
      status = 'voided',
      payment_status = 'voided',
      voided_at = coalesce(voided_at, now()),
      updated_at = now()
    where id = p_order_id;

    update public.payments
    set status = 'voided'
    where order_id = p_order_id;

    return app_private.pos_order_payload(p_order_id, true)
      || jsonb_build_object('restored_items', '[]'::jsonb);
  end if;

  select id
    into v_location_id
  from public.inventory_locations
  where code = 'MAIN_STORE'
  limit 1;

  if v_location_id is null then
    raise exception 'MAIN_STORE inventory location is missing';
  end if;

  create temporary table if not exists pos_rpc_void_rows (
    variant_id uuid primary key,
    product_id bigint not null,
    product_sku text not null,
    variant_sku text not null,
    quantity integer not null check (quantity > 0),
    balance_id uuid not null,
    quantity_before integer not null,
    quantity_reserved integer not null,
    quantity_after integer not null
  ) on commit drop;

  create temporary table if not exists pos_rpc_void_items (
    variant_id uuid primary key,
    product_id bigint not null,
    product_sku text not null,
    variant_sku text not null,
    quantity integer not null check (quantity > 0)
  ) on commit drop;

  truncate table pos_rpc_void_items;
  truncate table pos_rpc_void_rows;

  insert into pos_rpc_void_items (
    variant_id,
    product_id,
    product_sku,
    variant_sku,
    quantity
  )
  select
    i.variant_id,
    min(i.product_id)::bigint as product_id,
    coalesce(nullif(btrim(min(i.product_sku)), ''), min(i.variant_sku)) as product_sku,
    min(i.variant_sku) as variant_sku,
    sum(i.quantity)::integer as quantity
  from public.sales_order_items i
  where i.order_id = p_order_id
  group by i.variant_id;

  if not exists (select 1 from pos_rpc_void_items) then
    raise exception 'order has no items';
  end if;

  for v_row in
    select
      i.variant_id,
      i.product_id,
      i.product_sku,
      i.variant_sku,
      i.quantity,
      b.id as balance_id,
      b.quantity_on_hand,
      b.quantity_reserved
    from pos_rpc_void_items i
    join public.inventory_balances b
      on b.variant_id = i.variant_id
     and b.location_id = v_location_id
    order by i.variant_id
    for update of b
  loop
    insert into pos_rpc_void_rows (
      variant_id,
      product_id,
      product_sku,
      variant_sku,
      quantity,
      balance_id,
      quantity_before,
      quantity_reserved,
      quantity_after
    )
    values (
      v_row.variant_id,
      v_row.product_id,
      coalesce(nullif(btrim(v_row.product_sku), ''), v_row.variant_sku),
      v_row.variant_sku,
      v_row.quantity,
      v_row.balance_id,
      v_row.quantity_on_hand,
      v_row.quantity_reserved,
      v_row.quantity_on_hand + v_row.quantity
    );
  end loop;

  if (select count(*) from pos_rpc_void_rows) <> (select count(*) from pos_rpc_void_items) then
    raise exception 'order has no items with MAIN_STORE inventory balance';
  end if;

  v_idempotency_prefix := 'pos_void:' || v_client_request_id || ':' || p_order_id::text;

  update public.inventory_balances b
  set
    quantity_on_hand = r.quantity_after,
    updated_at = now()
  from pos_rpc_void_rows r
  where b.id = r.balance_id;

  insert into public.stock_movements (
    variant_id,
    location_id,
    movement_type,
    quantity_delta,
    quantity_before,
    quantity_after,
    reason,
    source_type,
    source_id,
    idempotency_key,
    created_by
  )
  select
    r.variant_id,
    v_location_id,
    'return',
    r.quantity,
    r.quantity_before,
    r.quantity_after,
    v_reason,
    'pos_void',
    p_order_id::text,
    v_idempotency_prefix || ':' || r.variant_id::text,
    coalesce(v_created_by, 'admin')
  from pos_rpc_void_rows r;

  for v_row in
    select distinct product_id
    from pos_rpc_void_rows
  loop
    perform app_private.pos_sync_legacy_stock_from_erp(v_row.product_id);
  end loop;

  update public.sales_orders
  set
    status = 'voided',
    payment_status = 'voided',
    voided_at = now(),
    updated_at = now()
  where id = p_order_id;

  update public.payments
  set status = 'voided'
  where order_id = p_order_id;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'variant_id', variant_id,
      'variant_sku', variant_sku,
      'quantity_before', quantity_before,
      'quantity_after', quantity_after,
      'quantity_delta', quantity
    )
    order by variant_sku
  ), '[]'::jsonb)
    into v_restored_items
  from pos_rpc_void_rows;

  return app_private.pos_order_payload(p_order_id, false)
    || jsonb_build_object('restored_items', v_restored_items);
end;
$$;

drop function if exists app_private.pos_checkout_rpc(text, text, jsonb, numeric, text, text);
drop function if exists app_private.pos_void_rpc(uuid, text, text, text);

revoke all on function app_private.pos_sync_legacy_stock_from_erp(bigint) from public;
revoke all on function app_private.pos_order_payload(uuid, boolean) from public;
revoke all on function public.pos_checkout_rpc(text, text, jsonb, numeric, text, text) from public;
revoke all on function public.pos_void_rpc(uuid, text, text, text) from public;

revoke execute on function app_private.pos_sync_legacy_stock_from_erp(bigint) from anon, authenticated;
revoke execute on function app_private.pos_order_payload(uuid, boolean) from anon, authenticated;
revoke execute on function public.pos_checkout_rpc(text, text, jsonb, numeric, text, text) from anon, authenticated;
revoke execute on function public.pos_void_rpc(uuid, text, text, text) from anon, authenticated;

grant execute on function public.pos_checkout_rpc(text, text, jsonb, numeric, text, text) to service_role;
grant execute on function public.pos_void_rpc(uuid, text, text, text) to service_role;

commit;

-- END MIGRATION: 20260705000100_add_pos_rpc_functions.sql

-- ============================================================================
-- BEGIN MIGRATION: 20260705000200_add_admin_users.sql
-- ============================================================================
begin;

create table if not exists public.admin_users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text,
  role text not null default 'staff',
  active boolean not null default true,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_users_role_check check (role in ('owner', 'staff', 'inventory', 'readonly')),
  constraint admin_users_email_not_blank_check check (btrim(email) <> '')
);

create index if not exists admin_users_email_idx
  on public.admin_users (lower(email));

create index if not exists admin_users_role_idx
  on public.admin_users (role);

create index if not exists admin_users_active_idx
  on public.admin_users (active);

alter table public.admin_users enable row level security;

revoke all on table public.admin_users from anon, authenticated;
grant select, insert, update, delete on table public.admin_users to service_role;

commit;

-- END MIGRATION: 20260705000200_add_admin_users.sql

-- ============================================================================
-- BEGIN MIGRATION: 20260707000100_add_feature_settings.sql
-- ============================================================================
begin;

create table if not exists public.feature_settings (
  id smallint primary key default 1,
  plan text not null default 'advanced',
  features jsonb not null default '{}'::jsonb,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint feature_settings_singleton_check check (id = 1),
  constraint feature_settings_plan_check check (plan in ('basic', 'standard', 'advanced', 'custom')),
  constraint feature_settings_features_object_check check (jsonb_typeof(features) = 'object')
);

insert into public.feature_settings (id, plan, features, updated_by)
values (
  1,
  'advanced',
  '{
    "storefront": true,
    "product_management": true,
    "inventory": true,
    "pos_checkout": true,
    "pos_orders": true,
    "pos_void": true,
    "pos_reports": true,
    "receipt_printing": true,
    "barcode_labels": true,
    "csv_import": true,
    "skroutz_feed": true,
    "staff_accounts": true,
    "ai_tools": true,
    "backup_tools": true
  }'::jsonb,
  'migration'
)
on conflict (id) do nothing;

alter table public.feature_settings enable row level security;

revoke all on table public.feature_settings from anon, authenticated;
grant select, insert, update, delete on table public.feature_settings to service_role;

commit;

-- END MIGRATION: 20260707000100_add_feature_settings.sql

-- ============================================================================
-- BEGIN MIGRATION: 20260707105854_add_legal_settings.sql
-- ============================================================================
begin;

create table if not exists public.legal_settings (
  id smallint primary key default 1,
  draft jsonb not null default '{}'::jsonb,
  is_complete boolean not null default false,
  current_version_number integer,
  published_at timestamptz,
  published_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by text,
  constraint legal_settings_singleton_check check (id = 1),
  constraint legal_settings_draft_object_check check (jsonb_typeof(draft) = 'object'),
  constraint legal_settings_version_positive_check check (current_version_number is null or current_version_number > 0)
);

create table if not exists public.legal_settings_versions (
  id bigint generated always as identity primary key,
  version_number integer not null unique,
  version_label text not null unique,
  snapshot jsonb not null,
  is_current boolean not null default false,
  published_at timestamptz not null default now(),
  published_by text,
  created_at timestamptz not null default now(),
  constraint legal_settings_versions_number_positive_check check (version_number > 0),
  constraint legal_settings_versions_label_check check (version_label = 'v' || version_number::text),
  constraint legal_settings_versions_snapshot_object_check check (jsonb_typeof(snapshot) = 'object')
);

create unique index if not exists legal_settings_versions_one_current_idx
  on public.legal_settings_versions (is_current)
  where is_current = true;

create index if not exists legal_settings_versions_published_at_idx
  on public.legal_settings_versions (published_at desc);

insert into public.legal_settings (id, draft, is_complete)
values (1, '{}'::jsonb, false)
on conflict (id) do nothing;

alter table public.legal_settings enable row level security;
alter table public.legal_settings_versions enable row level security;

revoke all on table public.legal_settings from anon, authenticated;
revoke all on table public.legal_settings_versions from anon, authenticated;

grant select, insert, update, delete on table public.legal_settings to service_role;
grant select, insert, update, delete on table public.legal_settings_versions to service_role;
grant usage, select on sequence public.legal_settings_versions_id_seq to service_role;

grant select on table public.legal_settings_versions to anon, authenticated;

drop policy if exists "Public can read current legal settings version" on public.legal_settings_versions;
create policy "Public can read current legal settings version"
  on public.legal_settings_versions
  for select
  to anon, authenticated
  using (is_current = true);

alter table public.sales_orders
  add column if not exists legal_terms_version text,
  add column if not exists privacy_policy_version text,
  add column if not exists legal_accepted_at timestamptz;

commit;

-- END MIGRATION: 20260707105854_add_legal_settings.sql

-- ============================================================================
-- BEGIN MIGRATION: 20260714131046_add_eu_sizes_and_supplier_fields.sql
-- ============================================================================
begin;

-- Some legacy customer databases predate the baseline migration and therefore
-- do not have this shared trigger helper. Keep this upgrade self-contained.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.suppliers (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  vat_number text,
  contact_name text,
  phone text,
  email text,
  address text,
  country text,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint suppliers_code_not_blank check (btrim(code) <> ''),
  constraint suppliers_name_not_blank check (btrim(name) <> '')
);

create index if not exists suppliers_active_name_idx
on public.suppliers (active, name);

drop trigger if exists suppliers_updated_at on public.suppliers;
create trigger suppliers_updated_at before update on public.suppliers
for each row execute function public.set_updated_at();

alter table public.products
  add column if not exists size_system text,
  add column if not exists supplier_id uuid references public.suppliers(id) on delete set null,
  add column if not exists supplier_style_code text,
  add column if not exists fiber_composition_gr text,
  add column if not exists fiber_composition_en text,
  add column if not exists care_instructions_gr text,
  add column if not exists care_instructions_en text,
  add column if not exists country_of_origin text,
  add column if not exists manufacturer_name text,
  add column if not exists manufacturer_contact text,
  add column if not exists eu_responsible_person text,
  add column if not exists product_safety_notes_gr text,
  add column if not exists product_safety_notes_en text;

alter table public.products
  drop constraint if exists products_size_system_check;
alter table public.products
  add constraint products_size_system_check check (
    size_system is null or size_system in (
      'letter',
      'eu_women_numeric',
      'eu_men_numeric',
      'eu_shoes',
      'one_size',
      'custom'
    )
  );

create index if not exists products_supplier_id_idx
on public.products (supplier_id);

create index if not exists products_supplier_style_code_idx
on public.products (supplier_style_code)
where supplier_style_code is not null and btrim(supplier_style_code) <> '';

alter table public.product_variants
  add column if not exists supplier_id uuid references public.suppliers(id) on delete set null,
  add column if not exists supplier_sku text,
  add column if not exists reorder_level integer;

alter table public.product_variants
  drop constraint if exists product_variants_reorder_level_check;
alter table public.product_variants
  add constraint product_variants_reorder_level_check check (
    reorder_level is null or reorder_level >= 0
  );

create index if not exists product_variants_supplier_sku_idx
on public.product_variants (supplier_sku)
where supplier_sku is not null and btrim(supplier_sku) <> '';

create unique index if not exists product_variants_supplier_sku_unique_idx
on public.product_variants (supplier_id, supplier_sku)
where supplier_id is not null and supplier_sku is not null and btrim(supplier_sku) <> '';

alter table public.suppliers enable row level security;
revoke all on table public.suppliers from anon, authenticated;
grant select, insert, update, delete on table public.suppliers to service_role;
grant select, insert, update, delete on table public.products to service_role;
grant select, insert, update, delete on table public.product_variants to service_role;

commit;

-- END MIGRATION: 20260714131046_add_eu_sizes_and_supplier_fields.sql

-- ============================================================================
-- BEGIN MIGRATION: 20260714234237_transactional_inventory_operations.sql
-- ============================================================================
begin;

create table if not exists public.inventory_operations (
  id uuid primary key default gen_random_uuid(),
  operation_key text not null unique,
  client_request_id text not null,
  operation_type text not null,
  variant_id uuid not null references public.product_variants(id) on delete restrict,
  location_id uuid not null references public.inventory_locations(id) on delete restrict,
  mode text not null,
  requested_quantity integer not null,
  quantity_before integer not null,
  quantity_after integer not null,
  quantity_delta integer not null,
  reason text not null,
  source_type text not null,
  source_id text not null,
  actor text not null,
  auto_deactivate boolean not null default false,
  result jsonb not null,
  created_at timestamptz not null default now(),
  constraint inventory_operations_type_check
    check (operation_type in ('manual', 'stocktake', 'receiving', 'return', 'quick_sell')),
  constraint inventory_operations_mode_check
    check (mode in ('set_to', 'adjust_by')),
  constraint inventory_operations_reason_not_blank_check
    check (btrim(reason) <> ''),
  constraint inventory_operations_actor_not_blank_check
    check (btrim(actor) <> ''),
  constraint inventory_operations_quantity_check
    check (
      quantity_before >= 0
      and quantity_after >= 0
      and quantity_delta = quantity_after - quantity_before
    )
);

create index if not exists inventory_operations_variant_created_idx
  on public.inventory_operations (variant_id, created_at desc);

create index if not exists inventory_operations_source_idx
  on public.inventory_operations (source_type, source_id);

alter table public.inventory_operations enable row level security;
revoke all on table public.inventory_operations from public, anon, authenticated;
grant select, insert, update, delete on table public.inventory_operations to service_role;

create or replace function public.inventory_apply_rpc(
  p_client_request_id text,
  p_variant_id uuid,
  p_mode text,
  p_quantity integer,
  p_operation_type text,
  p_reason text,
  p_created_by text,
  p_auto_deactivate boolean
)
returns jsonb
language plpgsql
security definer
set search_path = ''
set statement_timeout = '10s'
as $$
declare
  v_client_request_id text := pg_catalog.btrim(coalesce(p_client_request_id, ''));
  v_mode text := pg_catalog.btrim(coalesce(p_mode, ''));
  v_operation_type text := pg_catalog.btrim(coalesce(p_operation_type, ''));
  v_reason text := pg_catalog.btrim(coalesce(p_reason, ''));
  v_created_by text := pg_catalog.btrim(coalesce(p_created_by, ''));
  v_operation_key text;
  v_source_type text;
  v_movement_type text;
  v_location_id uuid;
  v_variant record;
  v_balance record;
  v_existing public.inventory_operations%rowtype;
  v_before integer;
  v_reserved integer;
  v_after integer;
  v_delta integer;
  v_stock integer := 0;
  v_size_stock jsonb := '{"ONE SIZE": 0}'::jsonb;
  v_sizes text := 'ONE SIZE';
  v_product_active boolean;
  v_result jsonb;
begin
  if v_client_request_id = '' or pg_catalog.length(v_client_request_id) > 128 then
    raise exception 'INVENTORY_INVALID_ARGUMENT: clientRequestId must contain 1 to 128 characters';
  end if;
  if p_variant_id is null then
    raise exception 'INVENTORY_INVALID_ARGUMENT: variantId is required';
  end if;
  if v_reason = '' or pg_catalog.length(v_reason) < 3 or pg_catalog.length(v_reason) > 500 then
    raise exception 'INVENTORY_INVALID_ARGUMENT: reason must contain 3 to 500 characters';
  end if;
  if v_created_by = '' or pg_catalog.length(v_created_by) > 200 then
    raise exception 'INVENTORY_INVALID_ARGUMENT: actor is required and must not exceed 200 characters';
  end if;
  if p_quantity is null or pg_catalog.abs(p_quantity::bigint) > 1000000 then
    raise exception 'INVENTORY_INVALID_ARGUMENT: quantity must be an integer between -1000000 and 1000000';
  end if;

  case v_operation_type
    when 'manual' then
      if v_mode not in ('set_to', 'adjust_by') then
        raise exception 'INVENTORY_INVALID_ARGUMENT: manual mode must be set_to or adjust_by';
      end if;
      if v_mode = 'set_to' and p_quantity < 0 then
        raise exception 'INVENTORY_INVALID_ARGUMENT: set_to quantity cannot be negative';
      end if;
      v_source_type := 'admin_inventory_adjustment';
      v_movement_type := 'manual_adjustment';
    when 'stocktake' then
      if v_mode <> 'set_to' or p_quantity < 0 then
        raise exception 'INVENTORY_INVALID_ARGUMENT: stocktake must set a non-negative quantity';
      end if;
      v_source_type := 'admin_stocktake';
      v_movement_type := 'correction';
    when 'receiving' then
      if v_mode <> 'adjust_by' or p_quantity <= 0 then
        raise exception 'INVENTORY_INVALID_ARGUMENT: receiving must add a positive quantity';
      end if;
      v_source_type := 'admin_receiving';
      v_movement_type := 'transfer_in';
    when 'return' then
      if v_mode <> 'adjust_by' or p_quantity <= 0 then
        raise exception 'INVENTORY_INVALID_ARGUMENT: return must add a positive quantity';
      end if;
      v_source_type := 'admin_customer_return';
      v_movement_type := 'return';
    when 'quick_sell' then
      if v_mode <> 'adjust_by' or p_quantity >= 0 then
        raise exception 'INVENTORY_INVALID_ARGUMENT: quick_sell must deduct a negative quantity';
      end if;
      v_source_type := 'quick_sell';
      v_movement_type := 'sale';
    else
      raise exception 'INVENTORY_INVALID_ARGUMENT: invalid operationType';
  end case;

  v_operation_key :=
    case when v_operation_type = 'quick_sell' then 'quick_sell:' else 'inventory:' end
    || v_client_request_id;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(v_operation_key, 0)
  );

  select *
    into v_existing
  from public.inventory_operations
  where operation_key = v_operation_key
  for update;

  if found then
    if v_existing.variant_id <> p_variant_id
      or v_existing.operation_type <> v_operation_type
      or v_existing.mode <> v_mode
      or v_existing.requested_quantity <> p_quantity
      or v_existing.reason <> v_reason
      or v_existing.actor <> v_created_by
      or v_existing.auto_deactivate <> coalesce(p_auto_deactivate, false)
    then
      raise exception 'INVENTORY_OPERATION_CONFLICT: operation ID was already used with different parameters';
    end if;

    return pg_catalog.jsonb_set(
      v_existing.result,
      '{alreadyProcessed}',
      'true'::jsonb,
      true
    );
  end if;

  select id
    into v_location_id
  from public.inventory_locations
  where code = 'MAIN_STORE'
    and active is distinct from false
  limit 1;

  if v_location_id is null then
    raise exception 'INVENTORY_NOT_FOUND: active MAIN_STORE location is missing';
  end if;

  select
    v.id,
    v.product_id,
    v.variant_sku,
    coalesce(nullif(pg_catalog.btrim(v.size), ''), 'ONE SIZE') as size,
    v.active as variant_active,
    p.sku as product_sku,
    p.is_active as product_active
    into v_variant
  from public.product_variants v
  join public.products p on p.id = v.product_id
  where v.id = p_variant_id
  for update of v, p;

  if not found then
    raise exception 'INVENTORY_NOT_FOUND: variant was not found';
  end if;

  if v_operation_type = 'quick_sell'
    and (v_variant.product_active is false or v_variant.variant_active is false)
  then
    raise exception 'INVENTORY_INACTIVE: product and variant must both be active';
  end if;

  if v_operation_type <> 'quick_sell' then
    insert into public.inventory_balances (
      variant_id,
      location_id,
      quantity_on_hand,
      quantity_reserved,
      updated_at
    ) values (
      p_variant_id,
      v_location_id,
      0,
      0,
      pg_catalog.now()
    )
    on conflict (variant_id, location_id) do nothing;
  end if;

  select id, quantity_on_hand, quantity_reserved
    into v_balance
  from public.inventory_balances
  where variant_id = p_variant_id
    and location_id = v_location_id
  for update;

  if not found then
    raise exception 'INVENTORY_NOT_FOUND: variant has no MAIN_STORE inventory balance';
  end if;

  v_before := v_balance.quantity_on_hand;
  v_reserved := v_balance.quantity_reserved;

  if v_operation_type = 'quick_sell'
    and (v_before - v_reserved) < (0 - p_quantity)
  then
    raise exception 'INVENTORY_INSUFFICIENT_AVAILABLE: requested %, available %',
      0 - p_quantity,
      greatest(v_before - v_reserved, 0);
  end if;

  v_after :=
    case
      when v_mode = 'set_to' then p_quantity
      else v_before + p_quantity
    end;

  if v_after < 0 then
    raise exception 'INVENTORY_INSUFFICIENT_STOCK: operation would make inventory negative';
  end if;
  if v_after < v_reserved then
    raise exception 'INVENTORY_RESERVED_CONFLICT: resulting on-hand quantity would be below reserved quantity';
  end if;

  v_delta := v_after - v_before;

  insert into public.inventory_operations (
    operation_key,
    client_request_id,
    operation_type,
    variant_id,
    location_id,
    mode,
    requested_quantity,
    quantity_before,
    quantity_after,
    quantity_delta,
    reason,
    source_type,
    source_id,
    actor,
    auto_deactivate,
    result
  ) values (
    v_operation_key,
    v_client_request_id,
    v_operation_type,
    p_variant_id,
    v_location_id,
    v_mode,
    p_quantity,
    v_before,
    v_after,
    v_delta,
    v_reason,
    v_source_type,
    v_operation_key,
    v_created_by,
    coalesce(p_auto_deactivate, false),
    '{}'::jsonb
  );

  if v_delta <> 0 then
    update public.inventory_balances
    set
      quantity_on_hand = v_after,
      updated_at = pg_catalog.now()
    where id = v_balance.id;

    if not found then
      raise exception 'INVENTORY_INVARIANT: locked balance disappeared';
    end if;

    insert into public.stock_movements (
      variant_id,
      location_id,
      movement_type,
      quantity_delta,
      quantity_before,
      quantity_after,
      reason,
      source_type,
      source_id,
      idempotency_key,
      created_by
    ) values (
      p_variant_id,
      v_location_id,
      v_movement_type,
      v_delta,
      v_before,
      v_after,
      v_reason,
      v_source_type,
      v_operation_key,
      v_operation_key,
      v_created_by
    );
  end if;

  with active_variants as (
    select
      coalesce(nullif(pg_catalog.btrim(v.size), ''), 'ONE SIZE') as size,
      v.sort_order,
      coalesce(b.quantity_on_hand, 0)::integer as quantity_on_hand
    from public.product_variants v
    left join public.inventory_balances b
      on b.variant_id = v.id
     and b.location_id = v_location_id
    where v.product_id = v_variant.product_id
      and v.active is distinct from false
  ),
  size_totals as (
    select
      size,
      pg_catalog.min(sort_order) as sort_order,
      pg_catalog.sum(quantity_on_hand)::integer as quantity_on_hand
    from active_variants
    group by size
  )
  select
    coalesce(pg_catalog.sum(quantity_on_hand), 0)::integer,
    coalesce(
      pg_catalog.jsonb_object_agg(size, quantity_on_hand order by sort_order, size),
      '{"ONE SIZE": 0}'::jsonb
    ),
    coalesce(
      pg_catalog.string_agg(size, ',' order by sort_order, size),
      'ONE SIZE'
    )
    into v_stock, v_size_stock, v_sizes
  from size_totals;

  update public.products
  set
    stock = v_stock,
    size_stock = v_size_stock,
    sizes = v_sizes,
    is_active = case
      when v_operation_type = 'quick_sell'
        and coalesce(p_auto_deactivate, false)
        and v_stock = 0
      then false
      else is_active
    end
  where id = v_variant.product_id
  returning is_active into v_product_active;

  if not found then
    raise exception 'INVENTORY_INVARIANT: product disappeared during legacy projection';
  end if;

  v_result := pg_catalog.jsonb_build_object(
    'ok', true,
    'rpc', true,
    'operationId', v_operation_key,
    'alreadyProcessed', false,
    'noChange', v_delta = 0,
    'operationType', v_operation_type,
    'variantId', p_variant_id,
    'variantSku', v_variant.variant_sku,
    'size', v_variant.size,
    'productId', v_variant.product_id,
    'productSku', v_variant.product_sku,
    'quantityBefore', v_before,
    'quantityAfter', v_after,
    'quantityDelta', v_delta,
    'quantityReserved', v_reserved,
    'quantityAvailable', v_after - v_reserved,
    'product', pg_catalog.jsonb_build_object(
      'id', v_variant.product_id,
      'sku', v_variant.product_sku,
      'stock', v_stock,
      'size_stock', v_size_stock,
      'sizes', v_sizes,
      'is_active', v_product_active
    )
  );

  update public.inventory_operations
  set result = v_result
  where operation_key = v_operation_key;

  insert into public.audit_logs (
    actor,
    action,
    entity,
    entity_id,
    before,
    after,
    metadata
  ) values (
    v_created_by,
    'inventory_operation',
    'product_variant',
    p_variant_id::text,
    pg_catalog.jsonb_build_object(
      'quantity_on_hand', v_before,
      'quantity_reserved', v_reserved
    ),
    pg_catalog.jsonb_build_object(
      'quantity_on_hand', v_after,
      'quantity_reserved', v_reserved
    ),
    pg_catalog.jsonb_build_object(
      'operation_key', v_operation_key,
      'operation_type', v_operation_type,
      'mode', v_mode,
      'requested_quantity', p_quantity,
      'source_type', v_source_type,
      'reason', v_reason
    )
  );

  return v_result;
end;
$$;

create or replace function public.inventory_runtime_health_rpc()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_apply regprocedure := pg_catalog.to_regprocedure(
    'public.inventory_apply_rpc(text,uuid,text,integer,text,text,text,boolean)'
  );
  v_executable boolean := false;
  v_operations_table regclass := pg_catalog.to_regclass('public.inventory_operations');
begin
  if v_apply is not null then
    v_executable := pg_catalog.has_function_privilege('service_role', v_apply, 'EXECUTE');
  end if;

  return pg_catalog.jsonb_build_object(
    'ready', v_apply is not null and v_executable and v_operations_table is not null,
    'version', 'inventory-transaction-v1',
    'apply_deployed', v_apply is not null,
    'apply_executable', v_executable,
    'operations_table_deployed', v_operations_table is not null
  );
end;
$$;

revoke execute on function public.inventory_apply_rpc(
  text, uuid, text, integer, text, text, text, boolean
) from public, anon, authenticated;
grant execute on function public.inventory_apply_rpc(
  text, uuid, text, integer, text, text, text, boolean
) to service_role;

revoke execute on function public.inventory_runtime_health_rpc()
  from public, anon, authenticated;
grant execute on function public.inventory_runtime_health_rpc()
  to service_role;

commit;

-- END MIGRATION: 20260714234237_transactional_inventory_operations.sql

-- ============================================================================
-- BEGIN MIGRATION: 20260715090000_add_developer_access.sql
-- ============================================================================
begin;

create table if not exists public.developer_access (
  id smallint primary key default 1,
  password_hash text not null,
  password_version integer not null default 1,
  updated_at timestamptz not null default now(),
  constraint developer_access_singleton_check check (id = 1),
  constraint developer_access_password_hash_not_blank_check check (btrim(password_hash) <> '')
);

alter table public.developer_access enable row level security;

revoke all on table public.developer_access from anon, authenticated;
grant select, insert, update on table public.developer_access to service_role;

insert into public.developer_access (id, password_hash, password_version)
values (
  1,
  'scrypt$16384$8$1$JVBQevdc5mVIsFKfhZYDBQ==$h57PoCu6BNPP/PWRxi3E3vt+eK1secqL+ZALrDolv/Xbn4V344uMobV9VCcVnJZgAmWf9XjJkcAN0KhGsihdBg==',
  1
)
on conflict (id) do nothing;

comment on table public.developer_access is
  'Private developer-only credential hash for Store Settings and Legal Settings. Never expose through anon/authenticated policies.';

commit;

-- END MIGRATION: 20260715090000_add_developer_access.sql

-- ============================================================================
-- BEGIN MIGRATION: 20260715100000_harden_pos_checkout_rpc.sql
-- ============================================================================
begin;

-- Keep the historical six-argument function for migration compatibility, but
-- remove direct Data API access. The new nine-argument wrapper is the only
-- supported checkout entry point and executes the old implementation inside
-- the same database transaction.
revoke execute on function public.pos_checkout_rpc(text, text, jsonb, numeric, text, text)
  from public, anon, authenticated, service_role;

create or replace function public.pos_checkout_rpc(
  p_client_request_id text,
  p_payment_method text,
  p_items jsonb,
  p_discount_total numeric,
  p_notes text,
  p_created_by text,
  p_legal_terms_version text,
  p_privacy_policy_version text,
  p_legal_accepted_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_client_request_id text := pg_catalog.btrim(coalesce(p_client_request_id, ''));
  v_result jsonb;
  v_order_id uuid;
  v_already_processed boolean;
begin
  if v_client_request_id = '' then
    raise exception 'client_request_id is required';
  end if;

  -- Serialize identical business operations before the historical RPC reads
  -- the idempotency key. A replay therefore returns the committed order rather
  -- than racing inventory locks and reporting a false stock conflict.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('pos_sale:' || v_client_request_id, 0)
  );

  v_result := public.pos_checkout_rpc(
    p_client_request_id,
    p_payment_method,
    p_items,
    p_discount_total,
    p_notes,
    p_created_by
  );

  v_order_id := nullif(v_result #>> '{order,id}', '')::uuid;
  v_already_processed := coalesce((v_result ->> 'already_processed')::boolean, false);

  if v_order_id is null then
    raise exception 'POS checkout RPC returned no order id';
  end if;

  if not v_already_processed then
    update public.sales_orders
    set
      legal_terms_version = nullif(pg_catalog.btrim(coalesce(p_legal_terms_version, '')), ''),
      privacy_policy_version = nullif(pg_catalog.btrim(coalesce(p_privacy_policy_version, '')), ''),
      legal_accepted_at = case
        when nullif(pg_catalog.btrim(coalesce(p_legal_terms_version, '')), '') is not null
          or nullif(pg_catalog.btrim(coalesce(p_privacy_policy_version, '')), '') is not null
        then coalesce(p_legal_accepted_at, pg_catalog.now())
        else null
      end,
      updated_at = pg_catalog.now()
    where id = v_order_id;

    if not found then
      raise exception 'POS checkout order % disappeared before legal acceptance was recorded', v_order_id;
    end if;
  end if;

  return v_result;
end;
$$;

create or replace function public.pos_runtime_health_rpc()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_checkout regprocedure := pg_catalog.to_regprocedure(
    'public.pos_checkout_rpc(text,text,jsonb,numeric,text,text,text,text,timestamp with time zone)'
  );
  v_void regprocedure := pg_catalog.to_regprocedure(
    'public.pos_void_rpc(uuid,text,text,text)'
  );
  v_checkout_executable boolean := false;
  v_void_executable boolean := false;
begin
  if v_checkout is not null then
    v_checkout_executable := pg_catalog.has_function_privilege('service_role', v_checkout, 'EXECUTE');
  end if;
  if v_void is not null then
    v_void_executable := pg_catalog.has_function_privilege('service_role', v_void, 'EXECUTE');
  end if;

  return pg_catalog.jsonb_build_object(
    'ready', v_checkout is not null and v_void is not null and v_checkout_executable and v_void_executable,
    'version', 'pos-transaction-v2',
    'checkout_deployed', v_checkout is not null,
    'checkout_executable', v_checkout_executable,
    'void_deployed', v_void is not null,
    'void_executable', v_void_executable
  );
end;
$$;

revoke execute on function public.pos_checkout_rpc(
  text, text, jsonb, numeric, text, text, text, text, timestamptz
) from public, anon, authenticated;
grant execute on function public.pos_checkout_rpc(
  text, text, jsonb, numeric, text, text, text, text, timestamptz
) to service_role;

revoke execute on function public.pos_runtime_health_rpc()
  from public, anon, authenticated;
grant execute on function public.pos_runtime_health_rpc()
  to service_role;

commit;

-- END MIGRATION: 20260715100000_harden_pos_checkout_rpc.sql

-- ============================================================================
-- BEGIN MIGRATION: 20260715100001_reconcile_pos_void_rpc.sql
-- ============================================================================
begin;

create or replace function public.pos_void_rpc(
  p_order_id uuid,
  p_client_request_id text,
  p_reason text,
  p_created_by text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_client_request_id text := pg_catalog.btrim(coalesce(p_client_request_id, ''));
  v_reason text := pg_catalog.btrim(coalesce(p_reason, ''));
  v_created_by text := nullif(pg_catalog.btrim(coalesce(p_created_by, '')), '');
  v_order_status text;
  v_location_id uuid;
  v_row record;
  v_expected_count integer;
  v_existing_count integer;
  v_missing_count integer;
  v_restored_items jsonb := '[]'::jsonb;
begin
  if p_order_id is null then
    raise exception 'order_id is required';
  end if;
  if v_client_request_id = '' then
    raise exception 'client_request_id is required';
  end if;
  if pg_catalog.length(v_reason) < 3 then
    raise exception 'reason is required and must be at least 3 characters';
  end if;
  if v_created_by is null then
    raise exception 'created_by is required';
  end if;

  select o.status
    into v_order_status
  from public.sales_orders o
  where o.id = p_order_id
  for update;

  if not found then
    raise exception 'POS order was not found';
  end if;
  if v_order_status = 'refunded' then
    raise exception 'refunded order cannot be voided';
  end if;
  if v_order_status not in ('completed', 'voided') then
    raise exception 'only completed orders can be voided';
  end if;

  select l.id
    into v_location_id
  from public.inventory_locations l
  where l.code = 'MAIN_STORE'
  limit 1;

  if v_location_id is null then
    raise exception using
      errcode = 'P0001',
      message = 'POS_VOID_RECONCILIATION_REQUIRED: MAIN_STORE inventory location is missing';
  end if;

  create temporary table if not exists pg_temp.pos_void_expected (
    variant_id uuid primary key,
    product_id bigint not null,
    product_sku text not null,
    variant_sku text not null,
    expected_quantity integer not null check (expected_quantity > 0),
    restored_quantity integer not null default 0,
    missing_quantity integer not null default 0
  ) on commit drop;

  create temporary table if not exists pg_temp.pos_void_rows (
    variant_id uuid primary key,
    product_id bigint not null,
    product_sku text not null,
    variant_sku text not null,
    balance_id uuid not null,
    restored_quantity integer not null,
    missing_quantity integer not null,
    quantity_before integer not null,
    quantity_after integer not null
  ) on commit drop;

  truncate table pg_temp.pos_void_expected;
  truncate table pg_temp.pos_void_rows;

  insert into pg_temp.pos_void_expected (
    variant_id,
    product_id,
    product_sku,
    variant_sku,
    expected_quantity
  )
  select
    i.variant_id,
    pg_catalog.min(i.product_id)::bigint,
    coalesce(nullif(pg_catalog.btrim(pg_catalog.min(i.product_sku)), ''), pg_catalog.min(i.variant_sku)),
    pg_catalog.min(i.variant_sku),
    pg_catalog.sum(i.quantity)::integer
  from public.sales_order_items i
  where i.order_id = p_order_id
  group by i.variant_id;

  select pg_catalog.count(*)::integer
    into v_expected_count
  from pg_temp.pos_void_expected;

  if v_expected_count = 0 then
    raise exception using
      errcode = 'P0001',
      message = 'POS_VOID_RECONCILIATION_REQUIRED: order has no item quantities to restore';
  end if;

  if exists (
    select 1
    from public.stock_movements m
    left join pg_temp.pos_void_expected e on e.variant_id = m.variant_id
    where m.source_type = 'pos_void'
      and m.source_id = p_order_id::text
      and (
        e.variant_id is null
        or m.location_id <> v_location_id
        or m.movement_type <> 'return'
        or m.quantity_delta <= 0
        or m.quantity_after <> m.quantity_before + m.quantity_delta
      )
  ) then
    raise exception using
      errcode = 'P0001',
      message = 'POS_VOID_RECONCILIATION_REQUIRED: existing void movements are inconsistent';
  end if;

  update pg_temp.pos_void_expected e
  set restored_quantity = restored.quantity
  from (
    select m.variant_id, pg_catalog.sum(m.quantity_delta)::integer as quantity
    from public.stock_movements m
    where m.source_type = 'pos_void'
      and m.source_id = p_order_id::text
    group by m.variant_id
  ) restored
  where restored.variant_id = e.variant_id;

  if exists (
    select 1
    from pg_temp.pos_void_expected e
    where e.restored_quantity < 0
       or e.restored_quantity > e.expected_quantity
  ) then
    raise exception using
      errcode = 'P0001',
      message = 'POS_VOID_RECONCILIATION_REQUIRED: restored quantity exceeds the order quantity';
  end if;

  update pg_temp.pos_void_expected
  set missing_quantity = expected_quantity - restored_quantity
  where true;

  select pg_catalog.count(*)::integer
    into v_existing_count
  from public.stock_movements m
  where m.source_type = 'pos_void'
    and m.source_id = p_order_id::text;

  -- A row marked voided without any restoration ledger cannot be safely
  -- distinguished from an old partial JS write that failed before movement
  -- insertion. Stop and require reconciliation instead of adding stock again.
  if v_order_status = 'voided' and v_existing_count = 0 then
    raise exception using
      errcode = 'P0001',
      message = 'POS_VOID_RECONCILIATION_REQUIRED: voided order has no restoration movements';
  end if;

  if exists (
    select 1
    from pg_temp.pos_void_expected e
    left join public.inventory_balances b
      on b.variant_id = e.variant_id
     and b.location_id = v_location_id
    where b.id is null
  ) then
    raise exception using
      errcode = 'P0001',
      message = 'POS_VOID_RECONCILIATION_REQUIRED: an order variant has no MAIN_STORE balance';
  end if;

  for v_row in
    select
      e.variant_id,
      e.product_id,
      e.product_sku,
      e.variant_sku,
      e.restored_quantity,
      e.missing_quantity,
      b.id as balance_id,
      b.quantity_on_hand
    from pg_temp.pos_void_expected e
    join public.inventory_balances b
      on b.variant_id = e.variant_id
     and b.location_id = v_location_id
    order by e.variant_id
    for update of b
  loop
    insert into pg_temp.pos_void_rows (
      variant_id,
      product_id,
      product_sku,
      variant_sku,
      balance_id,
      restored_quantity,
      missing_quantity,
      quantity_before,
      quantity_after
    ) values (
      v_row.variant_id,
      v_row.product_id,
      v_row.product_sku,
      v_row.variant_sku,
      v_row.balance_id,
      v_row.restored_quantity,
      v_row.missing_quantity,
      v_row.quantity_on_hand,
      v_row.quantity_on_hand + v_row.missing_quantity
    );
  end loop;

  if (select pg_catalog.count(*) from pg_temp.pos_void_rows) <> v_expected_count then
    raise exception using
      errcode = 'P0001',
      message = 'POS_VOID_RECONCILIATION_REQUIRED: not every order variant could be locked';
  end if;

  select pg_catalog.count(*)::integer
    into v_missing_count
  from pg_temp.pos_void_rows
  where missing_quantity > 0;

  if v_missing_count > 0 then
    update public.inventory_balances b
    set
      quantity_on_hand = r.quantity_after,
      updated_at = pg_catalog.now()
    from pg_temp.pos_void_rows r
    where b.id = r.balance_id
      and r.missing_quantity > 0;

    insert into public.stock_movements (
      variant_id,
      location_id,
      movement_type,
      quantity_delta,
      quantity_before,
      quantity_after,
      reason,
      source_type,
      source_id,
      idempotency_key,
      created_by
    )
    select
      r.variant_id,
      v_location_id,
      'return',
      r.missing_quantity,
      r.quantity_before,
      r.quantity_after,
      v_reason,
      'pos_void',
      p_order_id::text,
      'pos_void:' || v_client_request_id || ':' || p_order_id::text || ':' || r.variant_id::text,
      v_created_by
    from pg_temp.pos_void_rows r
    where r.missing_quantity > 0;

    for v_row in
      select distinct r.product_id
      from pg_temp.pos_void_rows r
      where r.missing_quantity > 0
    loop
      perform app_private.pos_sync_legacy_stock_from_erp(v_row.product_id);
    end loop;
  end if;

  update public.sales_orders
  set
    status = 'voided',
    payment_status = 'voided',
    voided_at = coalesce(voided_at, pg_catalog.now()),
    updated_at = pg_catalog.now()
  where id = p_order_id;

  update public.payments
  set status = 'voided'
  where order_id = p_order_id;

  select coalesce(
    pg_catalog.jsonb_agg(
      pg_catalog.jsonb_build_object(
        'variant_id', r.variant_id,
        'variant_sku', r.variant_sku,
        'quantity_before', r.quantity_before,
        'quantity_after', r.quantity_after,
        'quantity_delta', r.missing_quantity,
        'previously_restored', r.restored_quantity
      ) order by r.variant_sku
    ) filter (where r.missing_quantity > 0),
    '[]'::jsonb
  )
    into v_restored_items
  from pg_temp.pos_void_rows r;

  return app_private.pos_order_payload(p_order_id, v_missing_count = 0)
    || pg_catalog.jsonb_build_object('restored_items', v_restored_items);
end;
$$;

revoke execute on function public.pos_void_rpc(uuid, text, text, text)
  from public, anon, authenticated;
grant execute on function public.pos_void_rpc(uuid, text, text, text)
  to service_role;

commit;

-- END MIGRATION: 20260715100001_reconcile_pos_void_rpc.sql
