"use client";

import Image from "next/image";
import Link from "next/link";
import { useCart } from "@/components/cart-provider";
import { cartItemKey } from "@/lib/cart";
import type { Language } from "@/lib/i18n";

export function CartPageClient({ language, onlineStoreEnabled }: { language: Language; onlineStoreEnabled: boolean }) {
  const { items, ready, totals, setQuantity, removeItem } = useCart();
  const en = language === "en";
  if (!ready) return <div className="py-20 text-center text-stone-500">{en ? "Loading cart…" : "Φόρτωση καλαθιού…"}</div>;
  return <section className="ui-container py-8 sm:py-12"><div className="mb-8 flex items-end justify-between gap-4"><div><p className="ui-kicker">{en ? "Your selection" : "Οι επιλογές σας"}</p><h1 className="mt-2 text-3xl font-black text-ink sm:text-4xl">{en ? "Shopping cart" : "Καλάθι αγορών"}</h1></div><span className="text-sm font-bold text-stone-500">{totals.quantity} {en ? "items" : "τεμάχια"}</span></div>
    {items.length === 0 ? <div className="rounded-3xl border border-dashed border-stone-300 bg-white p-10 text-center"><p className="font-bold text-stone-600">{en ? "Your cart is empty." : "Το καλάθι σας είναι άδειο."}</p><Link className="ui-button-primary mt-6" href={en ? "/?lang=en" : "/"}>{en ? "Continue shopping" : "Συνέχεια αγορών"}</Link></div> : <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem]"><div className="space-y-3">{items.map(item => { const key=cartItemKey(item); return <article className="flex gap-4 rounded-2xl border border-stone-200 bg-white p-3 sm:p-4" key={key}><div className="relative h-28 w-24 shrink-0 overflow-hidden rounded-xl bg-stone-100">{item.imageUrl ? <Image alt={en ? item.nameEn : item.nameGr} className="object-cover" fill sizes="96px" src={item.imageUrl} /> : null}</div><div className="min-w-0 flex-1"><Link className="font-black text-ink hover:underline" href={`/product/${encodeURIComponent(item.productSku)}${en ? "?lang=en" : ""}`}>{en ? item.nameEn : item.nameGr}</Link><p className="mt-1 text-xs font-bold text-stone-500">{item.size}{item.color ? ` · ${item.color}` : ""}</p><p className="mt-2 font-black text-terracotta">€{item.unitPrice.toFixed(2)}</p><div className="mt-3 flex flex-wrap items-center gap-2"><button className="h-9 w-9 rounded-full border" onClick={() => setQuantity(key,item.quantity-1)} type="button">−</button><span className="min-w-8 text-center font-black">{item.quantity}</span><button className="h-9 w-9 rounded-full border" disabled={item.quantity>=Math.min(item.availableQuantity,20)} onClick={() => setQuantity(key,item.quantity+1)} type="button">+</button><button className="ml-auto min-h-9 px-2 text-xs font-bold text-red-600" onClick={() => removeItem(key)} type="button">{en ? "Remove" : "Αφαίρεση"}</button></div></div></article>; })}</div><aside className="h-fit rounded-3xl border border-stone-200 bg-white p-5 shadow-sm lg:sticky lg:top-28"><h2 className="text-lg font-black text-ink">{en ? "Order summary" : "Σύνοψη παραγγελίας"}</h2><div className="mt-5 flex justify-between border-t border-stone-100 pt-4"><span className="font-bold text-stone-600">{en ? "Subtotal" : "Υποσύνολο"}</span><span className="text-xl font-black">€{totals.subtotal.toFixed(2)}</span></div><p className="mt-2 text-xs leading-5 text-stone-500">{en ? "Delivery cost is calculated from the store settings at checkout. Pickup is free." : "Το κόστος παράδοσης υπολογίζεται στο ταμείο. Η παραλαβή από το κατάστημα είναι δωρεάν."}</p><Link aria-disabled={!onlineStoreEnabled} className={`mt-6 flex min-h-12 items-center justify-center rounded-full px-5 text-sm font-black ${onlineStoreEnabled ? "bg-ink text-white" : "pointer-events-none bg-stone-200 text-stone-400"}`} href={en ? "/checkout?lang=en" : "/checkout"}>{en ? "Checkout" : "Ολοκλήρωση παραγγελίας"}</Link></aside></div>}
  </section>;
}
