import { NextRequest, NextResponse } from "next/server";
import { authorizeAdminRequest } from "@/lib/admin-auth";
import { adminAuthorizationFailure } from "@/lib/admin-response";
import { featureDisabledResponse, isFeatureEnabled } from "@/lib/features";
import { getSupabaseAdminClient } from "@/lib/supabase";

export const dynamic="force-dynamic";
export async function GET(request:NextRequest){
  const authorization=await authorizeAdminRequest(request,"online_orders:read");if(!authorization.allowed)return adminAuthorizationFailure(authorization);
  if(!(await isFeatureEnabled("online_orders")))return featureDisabledResponse("online_orders");
  const supabase=getSupabaseAdminClient();if(!supabase)return NextResponse.json({error:"在线订单数据库未配置。",code:"ONLINE_ORDER_UNAVAILABLE"},{status:503});
  const url=new URL(request.url);const status=(url.searchParams.get("status")||"all").trim();const query=(url.searchParams.get("q")||"").trim().slice(0,120);const limit=Math.min(100,Math.max(1,Number(url.searchParams.get("limit"))||50));
  let db=(supabase as any).from("online_orders").select("id,order_number,status,fulfillment_method,fulfillment_status,payment_method,payment_status,subtotal,shipping_total,total,currency,customer_name,customer_email,customer_phone,customer_notes,locale,viva_order_code,viva_transaction_id,boxnow_locker_id,boxnow_locker_name,boxnow_locker_address,boxnow_locker_postal_code,pickup_code,pickup_ready_at,pickup_expires_at,paid_at,created_at,updated_at",{count:"exact"}).order("created_at",{ascending:false}).limit(limit);
  if(status.startsWith("fulfillment:"))db=db.eq("fulfillment_status",status.slice("fulfillment:".length));else if(status.startsWith("payment:"))db=db.eq("payment_status",status.slice("payment:".length));else if(status!=="all")db=db.eq("status",status);if(query)db=db.or(`order_number.ilike.%${query.replace(/[%(),]/g,"")}%,customer_name.ilike.%${query.replace(/[%(),]/g,"")}%,customer_phone.ilike.%${query.replace(/[%(),]/g,"")}%`);
  const{data,error,count}=await db;if(error){console.error("[online orders] list unavailable",{code:String(error.code||""),message:String(error.message||"")});return NextResponse.json({error:"在线订单读取失败。",code:"ONLINE_ORDER_UNAVAILABLE"},{status:503});}
  const ids=(data||[]).map((order:any)=>order.id);const{data:items,error:itemsError}=ids.length?await(supabase as any).from("online_order_items").select("order_id,product_sku,variant_sku,name_en,name_gr,size,color,quantity,unit_price,line_total,image_url").in("order_id",ids).order("created_at",{ascending:true}):{data:[],error:null};if(itemsError)return NextResponse.json({error:"在线订单明细读取失败。",code:"ONLINE_ORDER_UNAVAILABLE"},{status:503});
  const{data:shipments,error:shipmentsError}=ids.length?await(supabase as any).from("online_shipments").select("order_id,status,parcel_id,tracking_number,failure_code,provider_status,last_synced_at,updated_at,cancelled_at").in("order_id",ids):{data:[],error:null};if(shipmentsError)return NextResponse.json({error:"物流记录读取失败。",code:"ONLINE_ORDER_UNAVAILABLE"},{status:503});
  const{data:operations,error:operationsError}=ids.length?await(supabase as any).from("online_order_operations").select("order_id,action,actor,previous_status,next_status,note,created_at").in("order_id",ids).order("created_at",{ascending:false}):{data:[],error:null};if(operationsError)return NextResponse.json({error:"订单操作记录读取失败。",code:"ONLINE_ORDER_UNAVAILABLE"},{status:503});
  const{data:paymentEvents,error:paymentEventsError}=ids.length?await(supabase as any).from("online_payment_events").select("order_id,event_type,status,failure_code,received_at,processed_at").in("order_id",ids).order("received_at",{ascending:false}):{data:[],error:null};if(paymentEventsError)return NextResponse.json({error:"付款事件读取失败。",code:"ONLINE_ORDER_UNAVAILABLE"},{status:503});
  const byOrder=new Map<string,any[]>();for(const item of items||[]){const rows=byOrder.get(item.order_id)||[];rows.push(item);byOrder.set(item.order_id,rows);}const operationByOrder=new Map<string,any[]>();for(const item of operations||[]){const rows=operationByOrder.get(item.order_id)||[];rows.push(item);operationByOrder.set(item.order_id,rows);}const paymentByOrder=new Map<string,any[]>();for(const item of paymentEvents||[]){const rows=paymentByOrder.get(item.order_id)||[];rows.push(item);paymentByOrder.set(item.order_id,rows);}const shipmentByOrder=new Map((shipments||[]).map((shipment:any)=>[shipment.order_id,shipment]));return NextResponse.json({ok:true,total:count||0,orders:(data||[]).map((order:any)=>({...order,shipment:shipmentByOrder.get(order.id)||null,items:byOrder.get(order.id)||[],operations:operationByOrder.get(order.id)||[],payment_events:paymentByOrder.get(order.id)||[]}))});
}
