/**
 * Public products Data API contract.
 *
 * Every anonymous/authenticated consumer must select one of these explicit
 * DTOs. The union is mirrored by the products column-level SELECT grant in the
 * public data boundary migration. Procurement, Chinese admin copy, internal
 * barcode identity, and concurrency/version fields intentionally stay private.
 */
export const PUBLIC_PRODUCT_COLUMN_GRANT_COLUMNS = [
  "id",
  "sku",
  "name_gr",
  "name_en",
  "description_gr",
  "description_en",
  "category",
  "subcategory",
  "price",
  "stock",
  "sizes",
  "size_system",
  "size_stock",
  "image_url",
  "image_urls",
  "image_width",
  "image_height",
  "brand",
  "ean",
  "vat",
  "color",
  "additional_image_urls",
  "skroutz_url",
  "material",
  "fit",
  "season",
  "mpn",
  "availability",
  "size_chart",
  "fit_type",
  "ai_keywords",
  "material_verified",
  "category_path_en",
  "category_path_gr",
  "fiber_composition_gr",
  "fiber_composition_en",
  "care_instructions_gr",
  "care_instructions_en",
  "country_of_origin",
  "manufacturer_name",
  "manufacturer_contact",
  "eu_responsible_person",
  "product_safety_notes_gr",
  "product_safety_notes_en",
  "is_active",
  "created_at",
  "updated_at",
] as const;

export const PUBLIC_PRODUCT_LIST_COLUMNS = [
  "id",
  "sku",
  "name_gr",
  "name_en",
  "category",
  "subcategory",
  "price",
  "stock",
  "sizes",
  "size_system",
  "size_stock",
  "image_url",
  "image_urls",
  "is_active",
  "created_at",
] as const;

export const PUBLIC_PRODUCT_DETAIL_COLUMNS = [
  "id",
  "sku",
  "name_gr",
  "name_en",
  "description_gr",
  "description_en",
  "category",
  "subcategory",
  "price",
  "stock",
  "sizes",
  "size_system",
  "size_stock",
  "image_url",
  "image_urls",
  "brand",
  "ean",
  "vat",
  "color",
  "additional_image_urls",
  "skroutz_url",
  "material",
  "fiber_composition_gr",
  "fiber_composition_en",
  "care_instructions_gr",
  "care_instructions_en",
  "country_of_origin",
  "manufacturer_name",
  "manufacturer_contact",
  "eu_responsible_person",
  "product_safety_notes_gr",
  "product_safety_notes_en",
  "fit",
  "season",
  "mpn",
  "availability",
  "category_path_en",
  "category_path_gr",
  "size_chart",
  "fit_type",
  "material_verified",
  "is_active",
  "updated_at",
  "created_at",
] as const;

export const AI_PRODUCT_COLUMNS = [
  "sku",
  "name_en",
  "name_gr",
  "category",
  "subcategory",
  "price",
  "stock",
  "sizes",
  "size_system",
  "size_stock",
  "size_chart",
  "fit_type",
  "material",
  "material_verified",
  "ai_keywords",
  "image_url",
  "color",
  "brand",
  "is_active",
  "created_at",
] as const;

export const SKROUTZ_PRODUCT_COLUMNS = [
  "id",
  "sku",
  "name_gr",
  "name_en",
  "description_gr",
  "description_en",
  "category",
  "subcategory",
  "price",
  "stock",
  "size_stock",
  "sizes",
  "image_url",
  "image_urls",
  "additional_image_urls",
  "image_width",
  "image_height",
  "brand",
  "ean",
  "vat",
  "color",
  "mpn",
  "availability",
  "material",
  "fiber_composition_gr",
  "fiber_composition_en",
  "country_of_origin",
  "category_path_en",
  "category_path_gr",
  "is_active",
  "created_at",
] as const;

export const SITEMAP_PRODUCT_COLUMNS = [
  "sku",
  "created_at",
  "updated_at",
  "is_active",
] as const;

export const PUBLIC_PRODUCT_LIST_SELECT = PUBLIC_PRODUCT_LIST_COLUMNS.join(",");
export const PUBLIC_PRODUCT_DETAIL_SELECT = PUBLIC_PRODUCT_DETAIL_COLUMNS.join(",");
export const AI_PRODUCT_SELECT = AI_PRODUCT_COLUMNS.join(",");
export const SKROUTZ_PRODUCT_SELECT = SKROUTZ_PRODUCT_COLUMNS.join(",");
export const SITEMAP_PRODUCT_SELECT = SITEMAP_PRODUCT_COLUMNS.join(",");
