begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  sku text unique not null,
  name_cn text not null default '',
  name_gr text not null default '',
  name_en text not null default '',
  description_cn text not null default '',
  description_gr text not null default '',
  description_en text not null default '',
  category text not null,
  subcategory text not null default '',
  price numeric(10,2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  sizes text not null default '',
  size_stock jsonb not null default '{}'::jsonb check (jsonb_typeof(size_stock) = 'object'),
  image_url text not null default '',
  image_urls jsonb not null default '[]'::jsonb check (jsonb_typeof(image_urls) = 'array'),
  image_width integer,
  image_height integer,
  brand text not null default '',
  barcode text not null default '',
  ean text not null default '',
  vat numeric(5,2) not null default 24,
  color text not null default '',
  additional_image_urls text not null default '',
  skroutz_url text not null default '',
  material text not null default '',
  fit text not null default '',
  season text not null default '',
  mpn text not null default '',
  availability text not null default '',
  size_chart jsonb not null default '{}'::jsonb check (jsonb_typeof(size_chart) = 'object'),
  fit_type text not null default 'regular',
  style_tags text[] not null default '{}',
  ai_keywords text[] not null default '{}',
  material_verified boolean not null default false,
  category_path_en text not null default '',
  category_path_gr text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_sku_idx on public.products (sku);
create index if not exists products_created_at_idx on public.products (created_at desc);
create index if not exists products_category_idx on public.products (category);
create index if not exists products_category_subcategory_idx on public.products (category, subcategory);
create index if not exists products_is_active_idx on public.products (is_active);

drop trigger if exists products_updated_at on public.products;
create trigger products_updated_at before update on public.products
for each row execute function public.set_updated_at();

create table if not exists public.business_settings (
  id uuid primary key default gen_random_uuid(),
  business_name text not null default 'Fashion Boutique',
  logo_url text not null default '',
  hero_image_url text not null default '',
  description_cn text not null default '',
  description_en text not null default '',
  description_gr text not null default '',
  phone text not null default '',
  whatsapp text not null default '',
  instagram text not null default '',
  facebook text not null default '',
  tiktok text not null default '',
  address text not null default '',
  google_maps_url text not null default '',
  opening_hours text not null default '',
  footer_text text not null default '',
  enable_skroutz boolean not null default false,
  feed_min_stock integer not null default 1 check (feed_min_stock >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists settings_updated_at on public.business_settings;
create trigger settings_updated_at before update on public.business_settings
for each row execute function public.set_updated_at();

insert into public.business_settings (business_name, description_cn, description_en, description_gr)
select 'Fashion Boutique', '欢迎来到我们的在线商店。', 'Welcome to our online store.', 'Καλώς ήρθατε στο ηλεκτρονικό μας κατάστημα.'
where not exists (select 1 from public.business_settings);

create table if not exists public.product_categories (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name_cn text not null default '',
  name_en text not null default '',
  name_gr text not null default '',
  image_url text not null default '',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists product_categories_sort_order_idx on public.product_categories (sort_order);
drop trigger if exists categories_updated_at on public.product_categories;
create trigger categories_updated_at before update on public.product_categories
for each row execute function public.set_updated_at();

create table if not exists public.product_subcategories (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.product_categories(id) on delete cascade,
  slug text not null,
  name_cn text not null default '',
  name_en text not null default '',
  name_gr text not null default '',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (category_id, slug)
);

create index if not exists product_subcategories_category_id_idx on public.product_subcategories (category_id);
create index if not exists product_subcategories_sort_order_idx on public.product_subcategories (sort_order);
drop trigger if exists subcategories_updated_at on public.product_subcategories;
create trigger subcategories_updated_at before update on public.product_subcategories
for each row execute function public.set_updated_at();

alter table public.products enable row level security;
alter table public.business_settings enable row level security;
alter table public.product_categories enable row level security;
alter table public.product_subcategories enable row level security;

revoke all on table public.products, public.business_settings, public.product_categories, public.product_subcategories from anon, authenticated;
grant select on table public.products, public.business_settings, public.product_categories, public.product_subcategories to anon, authenticated;
grant select, insert, update, delete on table public.products, public.business_settings, public.product_categories, public.product_subcategories to service_role;
grant usage, select on sequence public.products_id_seq to service_role;

drop policy if exists "Public read active products" on public.products;
create policy "Public read active products" on public.products for select to anon, authenticated
using (is_active = true);

drop policy if exists "Public read business settings" on public.business_settings;
create policy "Public read business settings" on public.business_settings for select to anon, authenticated
using (true);

drop policy if exists "Public read active categories" on public.product_categories;
create policy "Public read active categories" on public.product_categories for select to anon, authenticated
using (is_active = true);

drop policy if exists "Public read active subcategories" on public.product_subcategories;
create policy "Public read active subcategories" on public.product_subcategories for select to anon, authenticated
using (is_active = true);

insert into public.product_categories (slug, name_cn, name_en, name_gr, sort_order) values
  ('women', '女装', 'Women', 'Γυναικεία', 1),
  ('men', '男装', 'Men', 'Ανδρικά', 2),
  ('shoes', '鞋子', 'Shoes', 'Παπούτσια', 3),
  ('bags', '包包', 'Bags', 'Τσάντες', 4),
  ('luggage', '行李箱', 'Luggage', 'Βαλίτσες', 5),
  ('hats', '帽子', 'Hats', 'Καπέλα', 6),
  ('jewelry', '首饰', 'Jewelry', 'Κοσμήματα', 7),
  ('other', '其他', 'Other', 'Άλλα', 8)
on conflict (slug) do nothing;

insert into public.product_subcategories (category_id, slug, name_cn, name_en, name_gr, sort_order)
select c.id, s.slug, s.name_cn, s.name_en, s.name_gr, s.sort_order
from public.product_categories c
cross join lateral (
  values
    ('women', 'dresses', '连衣裙', 'Dresses', 'Φορέματα', 1),
    ('women', 'tops', '上衣', 'Tops', 'Τοπ', 2),
    ('women', 'shirts', '衬衫', 'Shirts', 'Πουκάμισα', 3),
    ('women', 'hoodies', '卫衣', 'Hoodies', 'Φούτερ', 4),
    ('women', 'jackets', '外套', 'Jackets', 'Μπουφάν', 5),
    ('women', 'trousers', '长裤', 'Trousers', 'Παντελόνια', 6),
    ('women', 'skirts', '半身裙', 'Skirts', 'Φούστες', 7),
    ('men', 'tshirts', 'T恤', 'T-shirts', 'T-shirts', 1),
    ('men', 'shirts', '衬衫', 'Shirts', 'Πουκάμισα', 2),
    ('men', 'hoodies', '卫衣', 'Hoodies', 'Φούτερ', 3),
    ('men', 'jackets', '外套', 'Jackets', 'Μπουφάν', 4),
    ('men', 'trousers', '长裤', 'Trousers', 'Παντελόνια', 5),
    ('men', 'jeans', '牛仔裤', 'Jeans', 'Τζιν', 6),
    ('men', 'shorts', '短裤', 'Shorts', 'Σορτς', 7),
    ('shoes', 'sneakers', '运动鞋', 'Sneakers', 'Sneakers', 1),
    ('shoes', 'boots', '靴子', 'Boots', 'Μπότες', 2),
    ('shoes', 'sandals', '凉鞋', 'Sandals', 'Σανδάλια', 3),
    ('shoes', 'heels', '高跟鞋', 'Heels', 'Γόβες', 4),
    ('bags', 'handbags', '手提包', 'Handbags', 'Τσάντες χειρός', 1),
    ('bags', 'backpacks', '双肩包', 'Backpacks', 'Σακίδια', 2),
    ('bags', 'wallets', '钱包', 'Wallets', 'Πορτοφόλια', 3),
    ('luggage', 'suitcases', '行李箱', 'Suitcases', 'Βαλίτσες', 1),
    ('luggage', 'travel_bags', '旅行包', 'Travel Bags', 'Ταξιδιωτικές τσάντες', 2),
    ('hats', 'caps', '鸭舌帽', 'Caps', 'Καπέλα', 1),
    ('hats', 'beanies', '针织帽', 'Beanies', 'Σκούφοι', 2),
    ('jewelry', 'necklaces', '项链', 'Necklaces', 'Κολιέ', 1),
    ('jewelry', 'bracelets', '手链', 'Bracelets', 'Βραχιόλια', 2),
    ('jewelry', 'earrings', '耳环', 'Earrings', 'Σκουλαρίκια', 3),
    ('jewelry', 'rings', '戒指', 'Rings', 'Δαχτυλίδια', 4),
    ('other', 'accessories', '配饰', 'Accessories', 'Αξεσουάρ', 1)
) as s(category_slug, slug, name_cn, name_en, name_gr, sort_order)
where c.slug = s.category_slug
on conflict (category_id, slug) do nothing;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = excluded.public;

commit;
